// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://keymfylpyvpitmizplfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtleW1meWxweXZwaXRtaXpwbGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mzc5MDgsImV4cCI6MjA2OTMxMzkwOH0.ogfOgt_3ehLGUg6y6pEJG2D_3OjWQvkbC2kJOOphkg4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});